# Generated by Django 4.2.9 on 2025-02-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(upload_to='cars/', verbose_name='Фото')),
                ('engine', models.CharField(max_length=50, verbose_name='Двигатель')),
                ('power', models.CharField(max_length=50, verbose_name='Мощность')),
                ('transmission', models.CharField(max_length=50, verbose_name='Коробка передач')),
                ('drive', models.CharField(max_length=50, verbose_name='Привод')),
                ('fuel_consumption', models.CharField(max_length=50, verbose_name='Расход топлива')),
                ('deposit', models.PositiveIntegerField(verbose_name='Залог')),
                ('price_per_day', models.PositiveIntegerField(verbose_name='Цена за сутки')),
            ],
        ),
    ]
